DL
N=23
FORMAT = FULLMATRIX DIAGONAL PRESENT
ROW LABELS:
Santiago_CAÑIZARES
Joan_CAPDEVILA
Carlos_MARCHENA
David_ALBELDA
Carles_PUYOL
Iván_HELGUERA
RAÚL_González
Rubén_BARAJA
Fernando_TORRES
Fernando_MORIENTES
Albert_LUQUE
García_GABRI
Daniel_ARANZUBIA
VICENTE_Rodríguez
_RAÚL_BRAVO
_XABI_ALONSO
Joseba_ETXEBERRIA
CÉSAR_Martín
_SÁNCHEZ_Joaquín
Hernández_XAVI
Juan_Carlos_VALERÓN
Gutiérrez_JUANITO
Iker_CASILLAS
COLUMN LABELS:
Santiago_CAÑIZARES
Joan_CAPDEVILA
Carlos_MARCHENA
David_ALBELDA
Carles_PUYOL
Iván_HELGUERA
RAÚL_González
Rubén_BARAJA
Fernando_TORRES
Fernando_MORIENTES
Albert_LUQUE
García_GABRI
Daniel_ARANZUBIA
VICENTE_Rodríguez
_RAÚL_BRAVO
_XABI_ALONSO
Joseba_ETXEBERRIA
CÉSAR_Martín
_SÁNCHEZ_Joaquín
Hernández_XAVI
Juan_Carlos_VALERÓN
Gutiérrez_JUANITO
Iker_CASILLAS
DATA:
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  5  4  3  0  3  0  0  0  0  4  3  6  0  0  2  0  0  4  0
  0  0  0  4  0  4  1  1  3  0  0  0  0  2  1  6  0  0 13  0  0  1  1
  0  0  0  4  5  0  2  0  0  0  0  0  0  3  2  5  0  0  3  0  0  4  2
  0  0  0  2  1  2  0  1  3  0  0  0  0  4  0  3  0  0  1  0  0  0  1
  0  0  0  0  1  0  1  0  0  0  1  0  0  1  1  2  0  0  1  0  0  0  1
  0  0  0  2  0  1  5  0  0  1  2  0  0  2  4  0  0  0  2  0  0  0  5
  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  4  2  1  0  2  3  0  1  0  0  0  5  2  0  0  1  0  0  2  2
  0  0  0  1  1  0  0  1  4  1  0  0  0  9  0  6  0  0  1  0  0  3  1
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  1  2  1  1  5  0  1  0  0  2  3  2  0  0  1  0  0  3  0
