DL
N=23
FORMAT = FULLMATRIX DIAGONAL PRESENT
ROW LABELS:
Mickaël_LANDREAU
Jean-Alain_BOUMSONG
Bixente_LIZARAZU
Patrick_VIEIRA
William_GALLAS
Claude_MAKELELE
Robert_PIRES
Marcel_DESAILLY
Louis_SAHA
Zinédine_ZIDANE
Sylvain_WILTORD
Thierry_HENRY
Mikaël_SILVESTRE
Jérôme_ROTHEN
Lilian_THURAM
Fabien_BARTHEZ
Olivier_DACOURT
Benoît_PEDRETTI
Willy_SAGNOL
David_TREZEGUET
Steve_MARLET
Sidney_GOVOU
Grégory_COUPET
COLUMN LABELS:
Mickaël_LANDREAU
Jean-Alain_BOUMSONG
Bixente_LIZARAZU
Patrick_VIEIRA
William_GALLAS
Claude_MAKELELE
Robert_PIRES
Marcel_DESAILLY
Louis_SAHA
Zinédine_ZIDANE
Sylvain_WILTORD
Thierry_HENRY
Mikaël_SILVESTRE
Jérôme_ROTHEN
Lilian_THURAM
Fabien_BARTHEZ
Olivier_DACOURT
Benoît_PEDRETTI
Willy_SAGNOL
David_TREZEGUET
Steve_MARLET
Sidney_GOVOU
Grégory_COUPET
LEVEL LABELS:
1
DATA:
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  2  0  0  2  4  0  3  9  4  3  0  1 12  0  4  0  0  1  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  6  0  4  0  0  0  0  0  1  0  1  0  2  1  3  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  9  0  0 11  8  0  2  0  1  8  0  0  2  2  4  0  0  1  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  4  0  2  2  3  0  1  5  0  0  2  1  1  0  3  0  0  1  0  0  0
  0  0  2  0  6  7  1  0  1  3  0  2  0  1  8  7  4  0  0  1  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  4  0  5  7  3  0  0  3  1  4  9  0  0  4  3  0  0  0  0  0  0
  0  0  1  0  5  1  1  0  0  2  0  3  6  0  4  0  0  0  0  2  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  1  0  0  2  0  0  0  3  0  1  1  0  0  1  1  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
