DL
N=23
FORMAT = FULLMATRIX DIAGONAL PRESENT
ROW LABELS:
_RICARDO
_PAULO_FERREIRA
_RUI_JORGE
_JORGE_ANDRADE
Fernando_COUTO
_COSTINHA
_LUÍS_FIGO
_PETIT
_PAULETA
_RUI_COSTA
_Sabrosa_SIMÃO
_QUIM
_MIGUEL
_NUNO_VALENTE
_BETO
_RICARDO_CARVALHO
Cristiano_RONALDO
_MANICHE
_TIAGO
_DECO
_NUNO_GOMES
_MOREIRA
Hélder_POSTIGA
COLUMN LABELS:
_RICARDO
_PAULO_FERREIRA
_RUI_JORGE
_JORGE_ANDRADE
Fernando_COUTO
_COSTINHA
_LUÍS_FIGO
_PETIT
_PAULETA
_RUI_COSTA
_Sabrosa_SIMÃO
_QUIM
_MIGUEL
_NUNO_VALENTE
_BETO
_RICARDO_CARVALHO
Cristiano_RONALDO
_MANICHE
_TIAGO
_DECO
_NUNO_GOMES
_MOREIRA
Hélder_POSTIGA
DATA:
  0  0  0  2  0  0  1  0  1  0  0  0  1  1  0  2  1  1  0  1  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  0  0  0  0  2  3  0  1  0  0  0  1  6  0  3  1  7  0  5  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  0  0  2  0  2  0  0  2  0  0  0  1  2  0  0  0  5  0  8  1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  0  0  1  0  0  1  0  0  0  0  0  1  0  0  0  0  1  0  2  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  0  0  1  0  1  2  1  0  0  0  0  5  1  0  1  0  7  0  5  3  0  0
  1  0  0  5  1  3  5  1  3  0  0  0  0  5  0  2  7  0  0 18  1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  0  0  3  0  3 10  1  2  0  0  0  8  3  0  1  5  8  0  0  6  0  0
  0  0  0  0  1  0  1  1  0  0  0  0  1  1  0  0  2  4  0  4  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
