DL
N=23
FORMAT = FULLMATRIX DIAGONAL PRESENT
ROW LABELS:
_RICARDO
_PAULO_FERREIRA
_RUI_JORGE
_JORGE_ANDRADE
Fernando_COUTO
_COSTINHA
_LUÍS_FIGO
_PETIT
_PAULETA
_RUI_COSTA
_Sabrosa_SIMÃO
_QUIM
_MIGUEL
_NUNO_VALENTE
_BETO
_RICARDO_CARVALHO
Cristiano_RONALDO
_MANICHE
_TIAGO
_DECO
_NUNO_GOMES
_MOREIRA
Hélder_POSTIGA
COLUMN LABELS:
_RICARDO
_PAULO_FERREIRA
_RUI_JORGE
_JORGE_ANDRADE
Fernando_COUTO
_COSTINHA
_LUÍS_FIGO
_PETIT
_PAULETA
_RUI_COSTA
_Sabrosa_SIMÃO
_QUIM
_MIGUEL
_NUNO_VALENTE
_BETO
_RICARDO_CARVALHO
Cristiano_RONALDO
_MANICHE
_TIAGO
_DECO
_NUNO_GOMES
_MOREIRA
Hélder_POSTIGA
DATA:
  0  0  0  6  0  0  2  0  0  1  0  0  1  3  0  4  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  1  0  0  0  0  6  1  0  3  2  2  0  2  7  0  5  1  4  0  3  1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  4  0  0  6  0  0  2  1  0  5  7  0  4  0  6  0  6  0  0  0
  2  0  0  1  0  2  0  0  1  1  1  0  4  5  0  2  0  7  0 16  1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  1  0  0  0  2  0  1  2  0  1  0  1  0  1  0  0  0
  1  0  0  1  0  2  1  0  0  0  0  0  4  1  0  0  5  4  0  6  3  0  0
  0  0  0  0  0  1  1  0  2  0  0  0  1  4  0  0  0  1  0  3  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  1  0  0  0  0  0  4  0  0  0  1  0  0  0  1  0  0  1  0  0
  2  0  0  2  0 11  8  0  1  3  2  0 10  2  0  3  1  0  0 11  1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  1  0  1  9  0  4  5  4  0  2 10  0  3  0  6  0  0  3  0  0
  0  0  0  1  0  0  1  0  0  2  0  0  1  1  0  1  1  2  0  5  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
